#!/usr/bin/env zsh

echo -e "${c[green]}Operating System: ${c[cyan]}$(_tmux_uname)"

echo -e "${c[green]}Kernel: ${c[cyan]}$(uname -rm)"

echo -e "${c[green]}Hostname: ${c[cyan]}${HOST:-$HOSTNAME}"

echo -e "${c[green]}System Uptime: ${c[cyan]}$(_tmux_uptime)"

if [[ -f /var/log/auth.log ]]; then
  echo -e "${c[green]}Failed Login: ${c[cyan]}$(cat /var/log/auth.log 2>/dev/null | grep sshd | grep Fail | wc -l )"
else
  echo -e "${c[green]}Failed Login: ${c[cyan]}$( journalctl -u sshd 2>/dev/null | grep Fail | wc -l )"
fi

echo -en "${c[reset]}"
